### ISSUE TITLE
GA - Lista de V PTTO

### ISSUE THREAD

**Issue by lruiz1** [InteligenciaAnalitica/BER-Corp-RRMM#193]
10-	VERSIONES PRESUPUESTO: mail del 30/05/2019 14:40: que se vean las siguientes versiones de presupuesto: 
* PPTO_BDIC2015
* PPTO_BDIC2017
* PPTO_BJUN2018
* PPTO_BMAR2019
* Además del DEF que suponemos que es el que cargan los bancos.

**Comment by npzabala** [comment]
Se modifican reportes G1,G19 y TDP Corpo y Desvio PPTO Controlados para que muestren en la selección la lista de V.PPTO2 (contiene los valores y + pedidos por las chicas en el punto 10 del mail)
