### ISSUE TITLE
GA - Depurar Reportes WEBI

### ISSUE THREAD

**Issue by lruiz1** [InteligenciaAnalitica/BER-Corp-RRMM#270]
Se debera depurar los reportes mas pesasdos y eliminarlos

**Comment by npzabala** [comment]
![image.png](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/b998c56b-8286-4aa5-9be3-3f0a76cd48ca)

Solucion GEI, hoy 2/1
