### ISSUE TITLE
GA - Imputaciones BSC

### ISSUE THREAD

**Issue by lruiz1** [InteligenciaAnalitica/BER-Corp-RRMM#282]
Hola Roberto, pongo en copia al equipo para que puedan ayudarte, probablemente las imputaciones no estén viniendo en la IGGASINV.
Lucas Ruiz: podrás verificar esto en la IGGASINV_BSC de Corpo? 

mail: ju. 03/10/2019 16:44

**Comment by npzabala** [comment]
La imputación remarcada por alberto existe en la IGGASINV_BSC

![bsc1.jpg](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/83941789-637c-415f-abad-d5c3e4207cd5)

![bsc2.jpg](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/284b1696-ee4c-4e4e-bac0-d23cf78904ea)
