### ISSUE TITLE
GA - Filtros y Modif. G17

### ISSUE THREAD

**Issue by lruiz1** [InteligenciaAnalitica/BER-Corp-RRMM#327]
Chicos: por favor, ver estos dos reportes:
1)	G-17
![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/c1698a5e-b3e2-46a9-997a-6c1501ff05e8)

No trae movimientos para FOOD CORNER S.A.:
![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/a5afc3df-bc39-467d-847d-0cd6f84e31da)

2)	El reporte de Plan de Transformación Gastos:

![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/b1dcf7d3-62ac-4e53-a4b1-f370f1a4b59f)

Sí trae movimientos para FOOD CORNER:

![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/7deaaf1f-d89a-4b23-9e6e-064c5d23eae1)

**Comment by npzabala** [comment]
Se deben eliminar las pestañas de Plan de Transformación.
