### ISSUE TITLE
CA - Nuevo TDC Parametrizable

### ISSUE THREAD

**Issue by lruiz1** [InteligenciaAnalitica/BER-Corp-RRMM#62]

**Comment by PabloGottig** [comment]
Ahh entiendo como está armado.
Y si necesito irme más atrás, ejemplo “Dic’15 a Nov’16”, “Dic’16 a Nov’17” y “Dic’17 a Nov’18”? No puedo elegir periodos y escenarios? hay que modificar mucho el reporte?

![image.png](https://images.zenhubusercontent.com/5beef8c5308256459932e5c1/0f4e0659-b7fa-4336-8599-299554999497)

**Comment by lruiz1** [comment]
Lucas: 
              esto retomémoslo luego de cerrar los puntos de las prioridades que están con anterioridad. 

De igual manera, te paso lo que me pasó. Algo estoy haciendo mal, quiero elegir “Dic’15 a Nov’16”, “Dic’16 a Nov’17” y “Dic’17 a Nov’18”, Son tres periodos, necesito 4 escenarios para comprender todas las fechas; pero solo me trae dos periodos. ¿?¿?

![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/2ec50f7d-3991-4bd4-9436-de7b8f448a61)
