### ISSUE TITLE
BSC - NREP - Crear el Campo Tipo Cartera

### ISSUE THREAD

**Issue by lsartoriIA** [InteligenciaAnalitica/BER-Corp-RRMM#947]
•	Primera condición: colocar el “Tipo Cartera” según el producto que tengan el cliente utilizando el maestro que adjuntamos, el cual puede variar y se necesita que exista la posibilidad de actualizarlo.

•	Segunda condición: cuando el campo “MarcaComer” sea igual a “S” se debe asignar como “Tipo Cartera” la cartera “Comercial”.

•	Tercera condición: 
o	Cuando el campo “Atributo” sea igual a “4” el “Tipo Cartera” es igual a “Financiero”.
o	Si el “Atributo” es igual a “8” el “Tipo Cartera” es igual a “Publico”.
o	Si el “Atributo” es igual a “9” el “Tipo Cartera” es igual a “Publico”.
o	Si el “Atributo” es igual a “18” el “Tipo Cartera” es igual a “Irrecuperable”.

•	Cuarta condición: Si el campo “Tipo Cartera” sigue vacío completar con “Consumo”.

•	Quinta condición:   si el “CUIT” es superior a “30000000000” y el campo “Tipo Cartera” es igual a “Consumo” entonces reescribir y poner el “Tipo Cartera” igual a “Comercial Asimilable Consumo”

•	Sexta condición: Si el cliente posee algunos de estos productos 100, 103, 126 y128 en pesos y activo, se debe asigna en “Tipo Cartera” la cartera “Comercial Asimilable Consumo”. 
APLICAR SOLO A LOS TITULARES.
El campo nit que se encuentra dentro de la carpeta infocore inventario debe ser mayor que cero.
Codigo Sistemas Fuente = 1.

Comentarios:

Vos cuando asignas la cartera estás utilizando todos los productos que tiene el cliente y deberías utilizar sólo los que están en el inventario.
Y si el cliente tiene un producto consumo y uno comercial asimilable consumo, quedaría cómo comercial asimilable consumo

**Comment by PabloGottig** [comment]
PG: Ver cuestión de incompatibilidad que no permite la relaciones entre tablas.
